@base=localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhbGFuMTIzNDU2IiwiYXV0aG9yaXR5IjowLCJleHAiOjE2NTk0MzAxMzAsImlzcyI6InRvLWRvLWxpc3QifQ.YtFsYLwGbtO9ZheKMEugqvIDaqYOFGriP5JNW2SJZSE

### 查询所有 tasks
GET http://{{base}}/api/v1/tasks  HTTP/1.1
Authorization: {{token}}

### 新建任务
POST http://{{base}}/api/v1/task  HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "content": "好好干活",
  "status": 0,
  "title": "周二任务"
}

###
GET http://{{base}}/api/v1/task/6  HTTP/1.1
Authorization: {{token}}

### 模糊查询
POST http://{{base}}/api/v1/search  HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
  "info": "好好"
}

###
PUT http://{{base}}/api/v1/task/6  HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
  "id": 1,
  "content": "上班摸鱼11111",
  "status": 0,
  "title": "周一任务"
}

###
DELETE http://{{base}}/api/v1/task/6  HTTP/1.1
Authorization: {{token}}