@base=localhost:3000
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhbGFuMTIzNDU2IiwiYXV0aG9yaXR5IjowLCJleHAiOjE3NDMyNTA3NjYsImlzcyI6InRvLWRvLWxpc3QifQ.iVMpNJkGg59_icrywoYlZboTaid31T4rGddcXsCvSxY


###
GET http://{{base}}/api/v1/ping HTTP/1.1

### 先清空数据库数据再创建
POST http://{{base}}/api/v1/user/register HTTP/1.1
Content-Type: application/json

{
  "password": "alan123456",
  "user_name": "alan123456"
}

###
POST http://{{base}}/api/v1/user/login HTTP/1.1
Content-Type: application/json

{
  "password": "alan123456",
  "user_name": "alan123456"
}
